framework:
    default_locale: '%app.default_locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en

jms_i18n_routing:
    default_locale: '%app.default_locale%'
    locales: '%app.supported_locales%'
    strategy: prefix_except_default

jms_translation:
    configs:
        # so you can run ./bin/console translation:extract de --config=app
        # see http://jmsyst.com/bundles/JMSTranslationBundle/master/cookbook/extraction_configs
        app:
            dirs: ["%kernel.project_dir%/templates", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/translations"
            extractors: [jms_i18n_routing]
