twig:
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        # - '@TetranzSelect2Entity/Form/fields.html.twig'
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    globals:
        site_name: '%app.site.name%'
        locales: "%app.supported_locales%"
        site_matomo_id: '%app.site.matomo.id%'

when@test:
    twig:
        strict_variables: true
