# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.supported_locales: ['de', 'en']
    app.default_locale: 'de'
    app.site.name: "Hakhshara as a Place of Remembrance"

    app.mpdf-converter.arguments:
        config:
            fontDir: [ "%kernel.project_dir%/data/font" ]
            fontdata:
                pdffont:
                    R: 'SourceSansPro-Regular.ttf'
                    B: 'SourceSansPro-Bold.ttf'
                    I: 'SourceSansPro-Italic.ttf'
                    BI: 'SourceSansPro-BoldItalic.ttf'
            default_font: pdffont

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Utils\MpdfConverter:
        arguments: [ '%app.mpdf-converter.arguments%' ]

    # language-specific layout in 404
    App\EventListener\LanguageListener:
       arguments: [ '%jms_i18n_routing.default_locale%', '%jms_i18n_routing.locales%', '@jms_i18n_routing.locale_resolver' ]
       tags:
          - { name: kernel.event_listener, event: kernel.exception, method: setLocale }
